from modules import scripts, script_callbacks,shared
import gradio as gr
from nai_api_gen import nai_api

def script_setup():
    script_callbacks.on_ui_settings(on_ui_settings)

def on_ui_settings():
    section = ('nai_api', "NAI API Generator")
    def addopt(n,o):
        if not n in shared.opts.data_labels:
            shared.opts.add_option(n,o)
            
    addopt('nai_api_key', shared.OptionInfo('', "NAI API Key - See https://docs.sillytavern.app/usage/api-connections/novelai/ ", gr.Textbox, section=section))
    
    addopt('nai_api_skip_checks', shared.OptionInfo(False, "Skip NAI account/subscription/Anlas checks.",gr.Checkbox, section=section))
    addopt('nai_api_convertImportedWeights', shared.OptionInfo(True, "Convert NAI weights to A1111 when importing NAI prompts.",gr.Checkbox, section=section))
    
    addopt('nai_api_png_info', shared.OptionInfo( 'NAI Only', "Stealth PNG Info - Read/Write Stealth PNG info for NAI images only (required to emulate NAI), or All Images",gr.Radio, {"choices": ['NAI Only', 'All Images'] }, section=section))    
    
    addopt('nai_api_delay', shared.OptionInfo(0, "Minimum Time in seconds between successive API requests, may reduce Too Many Request errors.",gr.Slider, {"minimum":  0, "maximum": 32, "step": 1}, section=section))
    
    addopt('nai_api_delay_rand', shared.OptionInfo(0, "Random amount of time to wait between requests, adds a random value between 0 and n seconds to Minimum Time. May help avoid being incorrectly flagged as a bot.",gr.Slider, {"minimum":  0, "maximum": 32, "step": 1}, section=section))
    
    addopt('nai_api_timeout', shared.OptionInfo(120 , "Request Timeout - Time in seconds to wait before giving up on a request",gr.Slider, {"minimum":  30, "maximum": 360, "step": 5}, section=section))
    
    addopt('nai_api_retry', shared.OptionInfo(2, "Request Retry Attempts - Number of times to retry a failed request before giving up",gr.Slider, {"minimum": 0, "maximum": 3, "step": 1}, section=section))   
    
    
    addopt('nai_api_wait_on_429', shared.OptionInfo(30, "Maximum total time to wait before failing after receiving a 429 error (Too many requests).",gr.Slider, {"minimum": 0, "maximum": 3600, "step": 1}, section=section))
    
    addopt('nai_api_wait_on_429_time', shared.OptionInfo(5, "Time to wait between retry attempts after receiving a 429 error (Too many requests).",gr.Slider, {"minimum": 0, "maximum": 120, "step": 1}, section=section))
    
    
    addopt('nai_api_default_sampler', shared.OptionInfo('k_euler', "Fallback Sampler: Used when the NAI sampler is set to Auto and the primary Sampling method doesn't match any sampler available in NAI .",gr.Radio, {"choices": nai_api.NAI_SAMPLERS }, section=section))
    
    addopt('nai_metadata_only', shared.OptionInfo(False, "Save only NAI metadata instead of full local metadata. Local metadata can be useful for extensions, but contains irrelevant info.",gr.Checkbox, section=section))
    
    addopt('nai_api_include_original', shared.OptionInfo(True, "Include Original NAI images before Post-Processing in results.",gr.Checkbox, section=section))
    addopt('nai_api_save_original', shared.OptionInfo(False, "Save Original NAI images before Post-Processing.",gr.Checkbox, section=section))
    
    
    addopt('nai_api_all_images', shared.OptionInfo(False, "Include all images generated by NAI in the results.",gr.Checkbox, section=section))
    addopt('nai_api_save_fragments', shared.OptionInfo(False, "Save File Fragments generated by NAI while inpainting.",gr.Checkbox, section=section))
    
    addopt('nai_query_logging', shared.OptionInfo(False, "Log NAI API Queries to console.",gr.Checkbox, section=section))

    addopt('nai_verbose_logging', shared.OptionInfo(False, "Enable debug logging. IE Dump a bunch of garbage to the console.",gr.Checkbox, section=section))
        
    
        
def DEBUG_LOG(*args,**kwargs): 
    if shared.opts.data.get('nai_verbose_logging', False): 
        print(*args,**kwargs)
        
        